MACHINES = {
  :router1 => {
        :box_name => "ubuntu/focal64",
        :vm_name => "router1",
        :net => [
                   ['10.0.10.1', 2, "255.255.255.252", "r1-r2"],
                   ['10.0.12.1', 3, "255.255.255.252", "r1-r3"],
                   ['192.168.10.1', 4, "255.255.255.0", "net1"],
                   #{ip: '192.168.50.10', adapter: 5},
                ]
  },

  :router2 => {
        :box_name => "ubuntu/focal64",
        :vm_name => "router2",
        :net => [
                   ['10.0.10.2', 2, "255.255.255.252", "r1-r2"],
                   [ '10.0.11.2',3, "255.255.255.252", "r2-r3"],
                   ['192.168.20.1', 4, "255.255.255.0", "net2"],
                  #{ip: '192.168.50.11', adapter: 5},
             ]
  },

  :router3 => {
        :box_name => "ubuntu/focal64",
        :vm_name => "router3",
        :net => [
                   ['10.0.11.1', 2, "255.255.255.252", "r2-r3"],
                   [ '10.0.12.2', 3, "255.255.255.252", "r1-r3"],
                   [ '192.168.30.1', 4, "255.255.255.0", "net3"],
                   #{ip: '192.168.50.12', adapter: 5},
                ]
  }

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

 #    if boxconfig[:vm_name] == "router3"
 #     box.vm.provision "ansible" do |ansible|
 #       ansible.playbook = "ansible/provision.yml"
 #       ansible.inventory_path = "ansible/hosts"
 #       ansible.host_key_checking = "false"
 #       ansible.limit = "all"
 #      end
 #     end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

     end
  end
end


