---
- hosts: all
  become: yes
  tasks:
  - name: install packages
    yum: 
      name:
        - bind
        - bind-utils
        - ntp
        - vim
      state: latest
      update_cache: true  

  - name: stop and disable chronyd
    service: 
      name: chronyd
      state: stopped
      enabled: false
      
  - name: start and enable ntpd 
    service: 
      name: ntpd
      state: started
      enabled: true

  - name: copy transferkey to all servers and the client
    copy: src=named.zonetransfer.key dest=/etc/named.zonetransfer.key owner=root group=named mode=0644

- hosts: ns01
  become: yes
  tasks:
# Копирования файла named.conf
  - name: copy named.conf
    copy: 
      src: master-named.conf 
      dest: /etc/named.conf 
      owner: root
      group: named
      mode: 0640
  
  #Копирование файлов с настройками зоны
  - name: copy zones
    copy: 
      src: "{{ item }}" 
      dest: /etc/named/
      owner: root
      group: named
      mode: 0660
    with_items:
      - named.ddns.lab
      - named.dns.lab
      - named.dns.lab.client
      - named.dns.lab.rev
      - named.newdns.lab
  
  #Копирование файла resolv.conf на хосты
  - name: copy resolv.conf to the servers
    template: 
      src: servers-resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root 
      group: root 
      mode: 0644
  
  # Настройка прав для каталога /etc/named
  - name: set /etc/named permissions
    file: 
      path: /etc/named
      owner: root
      group: named 
      mode: 0670
  
  #Перезапуск и добавление в автозагрузку службы named
  - name: ensure named is running and enabled
    service: 
      name: named 
      state: restarted 
      enabled: yes

- hosts: ns02
  become: yes
  tasks:
  - name: copy named.conf
    copy: 
      src: slave-named.conf 
      dest: /etc/named.conf
      owner: root 
      group: named 
      mode: 0640

  - name: copy resolv.conf to the servers
    template: 
      src: servers-resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root 
      mode: 0644

  - name: set /etc/named permissions
    file: 
      path: /etc/named 
      owner: root 
      group: named 
      mode: 0670

  - name: ensure named is running and enabled
    service: 
      name: named 
      state: restarted 
      enabled: yes

    
- hosts: client
  become: yes
  tasks:
  - name: copy resolv.conf to the client
    copy: src=client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
  - name: copy rndc conf file
    copy: src=rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644
  - name: copy motd to the client
    copy: src=client-motd dest=/etc/motd owner=root group=root mode=0644

- hosts: client2
  become: yes
  tasks:
  - name: copy resolv.conf to the client
    copy: src=client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
  - name: copy rndc conf file
    copy: src=rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644
  - name: copy motd to the client
    copy: src=client-motd dest=/etc/motd owner=root group=root mode=0644
